"""correct fields in product schema

Revision ID: f3c263ec57fd
Revises: d6cbb4750e1b
Create Date: 2025-01-18 10:58:54.614521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3c263ec57fd'
down_revision: Union[str, None] = 'd6cbb4750e1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders_products_link', sa.Column('product_id', sa.Integer(), nullable=False))
    op.drop_constraint('orders_products_link_product_is_fkey', 'orders_products_link', type_='foreignkey')
    op.create_foreign_key(None, 'orders_products_link', 'products', ['product_id'], ['id'])
    op.drop_column('orders_products_link', 'product_is')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders_products_link', sa.Column('product_is', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders_products_link', type_='foreignkey')
    op.create_foreign_key('orders_products_link_product_is_fkey', 'orders_products_link', 'products', ['product_is'], ['id'])
    op.drop_column('orders_products_link', 'product_id')
    # ### end Alembic commands ###
