"""update order items asociation table

Revision ID: a613dac16765
Revises: 979c6b93882d
Create Date: 2024-12-12 15:00:41.717362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a613dac16765'
down_revision: Union[str, None] = '979c6b93882d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('idx_unique_order_item', 'order_items_association', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('idx_unique_order_item', 'order_items_association', ['order_id', 'item_id'])
    # ### end Alembic commands ###
